# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
future: true
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Plug-ins
plugins:
  - jekyll-feed
  - jekyll/scholar
 # - jekyll-sitemap
 # - jekyll-twitter-plugin


# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
#  style: apa
  style: generic-style-rules-for-linguistics
  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: papers.bib
  bibliography_template: "{{ reference |
  replace_first: 'Kuo, Jennifer', '<b>Kuo, Jennifer</b>' }}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  bibtex_filters:
    - latex
    - markdown
  query: "@*"
